[MKTXP]
    listen = 0.0.0.0:49090
    socket_timeout = 5
    
    initial_delay_on_failure = 120
    max_delay_on_failure = 900
    delay_inc_div = 5
    
    bandwidth = False
    bandwidth_test_interval = 600
    minimal_collect_interval = 5
    
    verbose_mode = False
    fetch_routers_in_parallel = False
    max_worker_threads = 5
    max_scrape_duration = 30
    total_max_scrape_duration = 90

# The section below contains the latest system parameters introduced by MKTXP
# For organizational purposes, you can move these parameters to the [MKTXP] section
[new_system_parameters]
    probe_connection_pool_ttl = 300
    probe_connection_pool_max_size = 128
    http_server_threads = 16
    probe_connection_pool = False
    persistent_router_connection_pool = True
    persistent_dhcp_cache = True
    prometheus_headers_deduplication = False
    compact_default_conf_values = False
    bandwidth_test_dns_server = 8.8.8.8
[DIAG]
    low_signal_threshold = -75
    min_signal_threshold = -60
    low_rate_threshold = 18M
    recent_duration = 15m
    top_connections_count = 10
    rate_above_threshold = 1M
    degraded_threshold = 100M
