[Mikrotik]
    enabled = True
    hostname = 192.168.0.1
    port = 50145
    
    username = mktxp
    password = pass
    
    use_ssl = False
    no_ssl_certificate = False
    ssl_certificate_verify = False
    plaintext_login = True
    
    installed_packages = True
    dhcp = True
    dhcp_lease = True
    pool = True
    interface = True
    monitor = True
    route = True
    firewall = True
    ipv6_firewall = False
    ipv6_neighbor = False
    connections = True
    connection_stats = True
    poe = False
    netwatch = False
    public_ip = True
    wireless = False
    wireless_clients = False
    capsman = False
    capsman_clients = False
    lte = False
    ipsec = False
    switch_port = True
    user = True
    queue = True
    bgp = False
    check_for_updates = False
    interface_name_format = comment
[default]

# The section below contains the latest default parameters introduced by MKTXP
# For organizational purposes, you can move these parameters to the [default] section
[new_default_parameters]
    interface = True
    user = True
    interface_with_default_name = False
    connection_stats = False
    total_address_list_counts = True
    routing_stats = False
    ipv6_neighbor = False
    health = True
    routerboard = False
    certificate = False
    neighbor = True
    dhcp = True
    monitor = True
    dns = False
    module_only = False
    wireless_clients = True
    netwatch = True
    w60g = False
    connection_stats_destinations = False
    installed_packages = True
    container = False
    poe = True
    switch_port = False
    no_ssl_certificate = False
    kid_control_dynamic = False
    ipv6_route = False
    kid_control_assigned = False
    firewall = True
    public_ip = True
    plaintext_login = True
    route = True
    ipv6_pool = False
    capsman = True
    wireguard_peers = False
    use_ssl = False
    bgp = False
    ipip = False
    ipsec = False
    queue = True
    connections = True
    bridge_vlan = False
    pool = True
    check_for_updates = False
    ssl_check_hostname = True
    enabled = False
    ipv6_firewall = False
    bfd = False
    dhcp_lease = True
    gre = False
    wireless = True
    eoip = False
    capsman_clients = True
    lte = False
    ipv6_total_address_list_counts = True
    ssl_certificate_verify = False
    hostname = localhost
    username = user
    password = password
    credentials_file = ""
    ssl_ca_file = ""
    remote_dhcp_entry = None
    remote_capsman_entry = None
    address_list = None
    ipv6_address_list = None
    custom_labels = None
    interface_name_format = name
    port = 8728
